#!/usr/bin/env python
# -*- coding: utf-8 -*-

__all__ = ['_http_cs_service_instance_template', '_protocol_set_temp', '_child_temp', '_service_root_instance_template']

_http_cs_service_instance_template = {
    "body": {
        "httpcsSvcInstance":
            {
                "protocolSets": [],
                "description": "httpcs instance generated by LLNW-SDK utils",
                "serviceProfileName": "",
                "publishedHostname": "",
                "sourceHostname": "",
                "publishedUrlPath": "",
                "sourceUrlPath": "",
                "serviceKey": {
                    "name": "httpcs"
                }

            },
        "childHttpcsSvcInstances": []
    },
    "accounts": [
        {
            "shortname": ""
        }
    ]
}

_protocol_set_temp = {
    "publishedProtocol": "https",
    "sourceProtocol": "https",
    "options": []
}

_child_temp = {
    "protocolSets": [],
    "description": "",
    "publishedUrlPath": "",
    "sourceUrlPath": "",
    "serviceKey": {}
}

_service_root_instance_template = {
    "protocolSets": [],
    "description": "",
    "serviceProfileName": "",
    "publishedHostname": "",
    "sourceHostname": "",
    "publishedUrlPath": "",
    "sourceUrlPath": "",
    "serviceKey": {
        "name": "httpcs"
    }}
